### PR TITLE
Preview action

### PR DESCRIPTION
**Pull request by bukhosi-eugene-mpande**
# Pull Request

**Description:**

Added action to create previews on vercel 

**Related Issues:**

**Type of Change:**

- [ ] Bug Fix
- [x] New Feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Documentation Update

**Additional Notes:**

### CODE REVIEW

**Comment by bukhosi-eugene-mpande** [comment]
DON'T MERGE

**Comment by bukhosi-eugene-mpande** [comment]
Its ok to merge the build is sucessful on the vercel side

**Review by JoshuaTristanWereley — APPROVED** [review]
Seems good to me.

**Review by ayandajuqu — APPROVED** [review]
looks good

**Pull request merged**
