### PR TITLE
Update/refactoring

### PR DESCRIPTION
**Pull request by bukhosi-eugene-mpande**
# Pull Request

**Description:**

Refactored some of the pages to reduce the number of line to maintain and test 

**Related Issues:**

[Reference any related issues or documents.]

**Type of Change:**

- [ ] Bug Fix
- [ ] New Feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Documentation Update

**Checklist:**

- [ ] I have read the [CONTRIBUTING.md](CONTRIBUTING.md) document.
- [ ] My code follows the coding standards of this project.
- [ ] I have performed a self-review of my code.
- [ ] I have added/updated relevant documentation.
- [ ] My changes generate no new warnings or errors.
- [ ] I have tested my changes.

**Reviewers:**

- @Ashley-Kapaso 
- @Lunga-Ntando-Ndlovu 

**Testing Instructions:**

[Provide clear and concise instructions on how to test your changes.]

**Screenshots (if applicable):**

[Add screenshots to help reviewers understand the changes visually.]

**Additional Notes:**

[Any additional information that may be helpful for reviewers.]

### CODE REVIEW

**Comment by Ashley-Kapaso** [comment]
Your branch has conflicts

**Review by Ashley-Kapaso — COMMENTED** [review]
This code looks beautiful 👏

**Comment by Ashley-Kapaso** [comment]
Your frontend tests are failing

**Review by Ashley-Kapaso — APPROVED** [review]
Perfect

**Review by Lunga-Ntando-Ndlovu — APPROVED** [review]
The code looks alright to me

**Pull request merged**
